# graph/graph_data_extractor.py
"""
Graph Data Extractor

Purpose:
---------
Convert dataset observations stored in CSV format into
Graph Neural Network training samples.

Input:
------
Unified observation CSV generated by:
    cad120_adapter.py
    cad60_adapter.py
    wut17_adapter.py
    wut18_adapter.py

Output:
-------
PyTorch Geometric graph objects:

Nodes:
    Scene
    Human
    Objects

Edges:
    Fully connected graph (Scene <-> Human <-> Objects)

Used by:
    reasoning/gnn_reasoner.py
    evaluate_system.py
"""
# graph/graph_data_extractor.py
"""
Graph Data Extractor (20-Joint / 60-Dimension Version)

Purpose:
Convert dataset observations into Graph Neural Network training samples.
Updated to support 20 skeletal joints (60 dims) for the human node.
"""

import os
import pandas as pd
import torch
import numpy as np
from torch_geometric.data import Data

# ============================================================
# Knowledge Graph Feature Configuration
# ============================================================
ACTION_CLASSES = ["a1","a2","a4","a5","a9"]

OBJECT_CLASSES = [
    "o_glass", "o_bottle", "o_computer", "o_doorknob", "o_milk", 
    "o_bowl", "o_object", "o_book", "o_phone", "o_microwave", 
    "o_table", "o_door"
]

SCENE_CLASSES = ["SC1", "SC2", "SC3", "SC4", "SC5"]

# --- 20-JOINT CONFIGURATION ---
# Excluded joints: 8, 9, 10, 15, 16, 17, 21, 25, 28, 29, 30, 31, 32, 33
INCLUDED_JOINTS = [
    0, 1, 2, 3, 4, 5, 6, 7, 
    11, 12, 13, 14, 
    18, 19, 20, 
    22, 23, 24, 
    26, 27
]
POSE_DIM = len(INCLUDED_JOINTS) * 3  # 20 joints * 3 coords = 60 dimensions


# ============================================================
# Node Feature Builder (60 Dimensions)
# ============================================================
def create_node_feature(row, node_type, scene_id, neo4j_session=None):
    """
    Node feature dimension = 60
    Human: 20 joints * 3 coords = 60
    Object: One-hot(12) + XYZ(3) + Prior(1) + Padding(44) = 60
    Scene: One-hot(5) + Padding(55) = 60
    """
    # Initialize all 60 dimensions to 0.0
    feature = [0.0] * POSE_DIM 

    if node_type == "human":
        # Extract the 20 specific joints from the CSV row
        # Assumes CSV has columns like 'joint_0_x', 'joint_0_y', 'joint_0_z', etc.
        for i, joint_id in enumerate(INCLUDED_JOINTS):
            x = row.get(f'joint_{joint_id}_x', 0.0)
            y = row.get(f'joint_{joint_id}_y', 0.0)
            z = row.get(f'joint_{joint_id}_z', 0.0)
            
            feature[i*3 + 0] = x
            feature[i*3 + 1] = y
            feature[i*3 + 2] = z

    elif node_type == "scene":
        # One-hot encode scene at the beginning (Indices 0-4), leave the rest as 0.0 padding
        if row.scene_id in SCENE_CLASSES:
            feature[SCENE_CLASSES.index(row.scene_id)] = 1.0

    elif node_type == "object":
        # 1. One-hot encoding (Indices 0-11)
        if row.object_id in OBJECT_CLASSES:
            feature[OBJECT_CLASSES.index(row.object_id)] = 1.0
        
        # 2. XYZ coordinates (Indices 12-14)
        feature[12] = row.object_x
        feature[13] = row.object_y
        feature[14] = row.object_z
        
        # 3. SYMBOLIC PRIORS (Index 15)
        if neo4j_session:
            try:
                res = neo4j_session.run(
                    "MATCH (s:Scene {scene_id: $sc})-[r:HAS_OBJECT]->(o:Object {object_id: $obj}) RETURN r.p as p",
                    sc=scene_id, obj=row.object_id
                ).single()
                scene_obj_p = res["p"] if res else 0.1
            except Exception:
                scene_obj_p = 0.5
            feature[15] = scene_obj_p
        else:
            feature[15] = 0.5
            
        # Indices 16 to 59 remain 0.0 (Padding)

    return feature

# ============================================================
# Edge Construction
# ============================================================
def build_edges(num_nodes):
    """Fully connected graph (Scene <-> Human <-> Objects)"""
    edges = []
    for i in range(num_nodes):
        for j in range(num_nodes):
            if i != j:
                edges.append([i, j])
    
    edge_index = torch.tensor(edges, dtype=torch.long).t().contiguous()
    return edge_index

# ============================================================
# Extract Graph From Single Observation
# ============================================================
def observation_to_graph(df):
    nodes = []
    row = df.iloc[0]
    scene_id = row.scene_id

    # Node 0: Scene
    nodes.append(create_node_feature(row, "scene", scene_id))
    
    # Node 1+: ALL detected humans (no limit)
    humans = df[df['human_id'].notna()]
    for _, human in humans.iterrows():
        nodes.append(create_node_feature(human, "human", scene_id))
    
    # Node N+: ALL detected objects (no limit)
    objects = df[~df['object_id'].str.contains('human|person', case=False, na=False)]
    for _, obj in objects.iterrows():
        nodes.append(create_node_feature(obj, "object", scene_id))

    # Action label
    action_id = row.action_id if row.action_id in ACTION_CLASSES else "a1"
    label = ACTION_CLASSES.index(action_id)

    x = torch.tensor(nodes, dtype=torch.float)
    edge_index = build_edges(len(nodes)) 
    y = torch.tensor([label], dtype=torch.long)

    return Data(x=x, edge_index=edge_index, y=y)

# ============================================================
# Dataset Loader
# ============================================================
def load_graph_dataset(csv_file):
    print("Loading CSV:", csv_file)
    df = pd.read_csv(csv_file)
    graphs = []

    grouped=df.groupby(["video_id","frame","action_instance_id"]
)
    for _, frame_data in grouped:
        try:
            g = observation_to_graph(frame_data)
            graphs.append(g)
        except Exception as e:
            print(f"\n[CRITICAL ERROR] Failed on frame {frame_data['frame'].iloc[0]}:")
            print(f"Error: {e}")
            import traceback
            traceback.print_exc()
            break 
            
    print(f"Generated graphs: {len(graphs)}")
    return graphs

def save_graph_dataset(graphs, filename="graph_dataset.pt"):
    torch.save(graphs, filename)
    print("Saved:", filename)

# ============================================================
# Main
# ============================================================
if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--csv", required=True, help="Unified observation csv")
    parser.add_argument("--output", default="graph_dataset_20joints.pt", help="Output pt file")
    args = parser.parse_args()

    graphs = load_graph_dataset(args.csv)
    save_graph_dataset(graphs, args.output)